# Generated by Django 4.1.3 on 2022-11-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_belong_user_belongs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
