# Generated by Django 4.1.3 on 2022-12-05 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0005_alter_nested_comment_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nested_comment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_comments",
                to="boards.comment",
            ),
        ),
    ]
